import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} antialiased [--nav-height:--spacing(16)] md:[--nav-height:--spacing(18)]`}
      >
        <Navbar />
        <div className="mt-[var(--nav-height)]">{children}</div>
        <Footer />
        <Toaster richColors />
      </body>
    </html>
  )
}
